[package]
name = "permutation_iterator"
version = "0.1.0"
authors = ["Asim Ihsan <asim.ihsan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "medium"

[dependencies]
blake2-rfc = "0.2.18"
rand = "0.7.2"
